CREATE TABLE ADDRESS (
    ID NUMBER(19,0) NOT NULL,
    CITY VARCHAR2(255 CHAR),
    POSTAL_CODE VARCHAR2(255 CHAR),
    STREET VARCHAR2(255 CHAR),
    STREET_NUMBER VARCHAR2(255 CHAR),
    PRIMARY KEY (ID)
);

CREATE TABLE AUTHOR (
    PUBLICATIONS NUMBER(10,0),
    AUTHOR_ID NUMBER(19,0) NOT NULL,
    PRIMARY KEY (AUTHOR_ID)
);

CREATE TABLE BOOK (
    ID NUMBER(19,0) NOT NULL,
    TITLE VARCHAR2(50 CHAR) NOT NULL,
    LIBRARY_ID NUMBER(19,0),
    PRIMARY KEY (ID)
);

CREATE TABLE BOOK_AUTHOR (
    BOOK_ID NUMBER(19,0) NOT NULL,
    AUTHOR_ID NUMBER(19,0) NOT NULL,
    PRIMARY KEY (BOOK_ID, AUTHOR_ID)
);

CREATE TABLE LIBRARY (
    ID NUMBER(19,0) NOT NULL,
    NAME VARCHAR2(255 CHAR),
    VERSION NUMBER(19,0) NOT NULL,
    ADDRESS_ID NUMBER(19,0),
    PRIMARY KEY (ID)
);

CREATE TABLE PERSON (
    ID NUMBER(19,0) NOT NULL,
    AGE NUMBER(10,0) NOT NULL,
    FIRST_NAME VARCHAR2(50 CHAR) NOT NULL,
    LAST_NAME VARCHAR2(50 CHAR) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE AUTHOR
    ADD CONSTRAINT FK_IGKJ4JV2TI0G2K5T99U5M68BL
    FOREIGN KEY (AUTHOR_ID)
    REFERENCES PERSON;

ALTER TABLE BOOK
    ADD CONSTRAINT FK_3PKEWPPFC8DYAHQOW87UPBEMB
    FOREIGN KEY (LIBRARY_ID)
    REFERENCES LIBRARY;

ALTER TABLE BOOK_AUTHOR
    ADD CONSTRAINT FK_6CMG2ROOPA9A4C97UXETGF2E9
    FOREIGN KEY (AUTHOR_ID)
    REFERENCES AUTHOR;

ALTER TABLE BOOK_AUTHOR
    ADD CONSTRAINT FK_Q37QKJ7SERXG0BH56M450UIGS
    FOREIGN KEY (BOOK_ID)
    REFERENCES BOOK;

ALTER TABLE LIBRARY
    ADD CONSTRAINT FK_44CXNDEXSNWYP4POO41JMHWVG
    FOREIGN KEY (ADDRESS_ID)
    REFERENCES ADDRESS;

CREATE SEQUENCE HIBERNATE_SEQUENCE;